language: node_js
node_js:
  - '10'

dist: trusty
sudo: required

branches:
only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build dmaterial-web --prod --base-href https://diegoavieira.github.io/dmaterial/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/dmaterial-web
  on:
    branch: master
